import { Box, Container, Heading, Text, VStack, useColorModeValue, Divider } from '@chakra-ui/react';
import { Helmet } from 'react-helmet-async';

const PrivacyPolicy = () => {
    const bgColor = useColorModeValue('white', 'gray.900');
    const headerBg = useColorModeValue('gray.50', 'black');
    const titleColor = useColorModeValue('gray.900', 'white');
    const contentColor = useColorModeValue('gray.700', 'gray.300');
    const cardBorder = useColorModeValue('gray.100', 'gray.800');

    return (
        <Box bg={bgColor} minH="100vh" pb={20}>
            <Helmet>
                <title>Privacy Policy | himarbi.</title>
                <meta name="description" content="Privacy Policy for himarbi.me" />
            </Helmet>

            {/* Header Section */}
            <Box bg={headerBg} pt={32} pb={20} position="relative" overflow="hidden">
                <Box position="absolute" top="0" left="0" right="0" h="400px" bgGradient="radial(brand.500, transparent)" filter="blur(150px)" opacity={useColorModeValue(0.1, 0.2)} zIndex={0} pointerEvents="none" />
                <Container maxW="container.md" position="relative" zIndex={1}>
                    <Heading as="h1" fontSize={{ base: '4xl', md: '5xl' }} fontFamily="'Playfair Display', serif" fontWeight="700" color={titleColor} mb={6}>
                        Privacy Policy
                    </Heading>
                    <Text fontSize="xl" color={contentColor}>
                        Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                    </Text>
                </Container>
            </Box>

            <Container maxW="container.md" mt={12}>
                <VStack spacing={8} align="start" color={contentColor} fontSize="lg" lineHeight="1.8">

                    <Box w="full">
                        <Heading as="h2" size="xl" mb={4} color={titleColor} fontFamily="'Playfair Display', serif">
                            1. Introduction
                        </Heading>
                        <Text>
                            Welcome to himarbi.me. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website and tell you about your privacy rights.
                        </Text>
                    </Box>

                    <Divider borderColor={cardBorder} />

                    <Box w="full">
                        <Heading as="h2" size="xl" mb={4} color={titleColor} fontFamily="'Playfair Display', serif">
                            2. Google AdSense & Cookies
                        </Heading>
                        <Text mb={4}>
                            This website uses Google AdSense, a service for including advertisements from Google Inc. ("Google"). Google AdSense uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site.
                        </Text>
                        <Text mb={4}>
                            Google AdSense also uses web beacons (invisible graphics). Through these web beacons, information such as the visitor traffic on these pages can be evaluated. The information generated by cookies and web beacons relating to the use of this website (including your IP address) and delivery of advertising formats are transmitted to a Google server in the US and stored there.
                        </Text>
                        <Text>
                            <strong>Google's Use of the DART Cookie:</strong>
                            <Box as="ul" pl={6} mt={2} mb={4}>
                                <li>Third party vendors, including Google, use cookies to serve ads based on a user's prior visits to your website or other websites.</li>
                                <li>Google's use of advertising cookies enables it and its partners to serve ads to your users based on their visit to your sites and/or other sites on the Internet.</li>
                                <li>Users may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer" style={{ color: '#805ad5', textDecoration: 'underline' }}>Ads Settings</a>.</li>
                            </Box>
                        </Text>
                    </Box>

                    <Divider borderColor={cardBorder} />

                    <Box w="full">
                        <Heading as="h2" size="xl" mb={4} color={titleColor} fontFamily="'Playfair Display', serif">
                            3. Data Collection
                        </Heading>
                        <Text>
                            We only collect personal information that you provide to us directly through forms on this website (like your name and email address when using the Contact or Comment features). This information is solely used to respond to your inquiries.
                        </Text>
                    </Box>

                    <Divider borderColor={cardBorder} />

                    <Box w="full">
                        <Heading as="h2" size="xl" mb={4} color={titleColor} fontFamily="'Playfair Display', serif">
                            4. Third-Party Links
                        </Heading>
                        <Text>
                            This website may include links to third-party websites, plug-ins, and applications. Clicking on those links or enabling those connections may allow third parties to collect or share data about you. We do not control these third-party websites and are not responsible for their privacy statements.
                        </Text>
                    </Box>

                    <Divider borderColor={cardBorder} />

                    <Box w="full">
                        <Heading as="h2" size="xl" mb={4} color={titleColor} fontFamily="'Playfair Display', serif">
                            5. Contact Information
                        </Heading>
                        <Text>
                            If you have any questions about this Privacy Policy or our privacy practices, please contact us via the email address listed in our footer or contact section.
                        </Text>
                    </Box>

                </VStack>
            </Container>
        </Box>
    );
};

export default PrivacyPolicy;
